### ISSUE TITLE
都是中国人，我就用中文留言了

### ISSUE THREAD

**Issue by thtTNT** [Jamling/SmartIM#5]
1、程序启动的时候根本不弹出登陆窗口
2、进入设置会有报错
2018-03-10 21:35:40.650 [AWT-EventQueue-0] WARN  (FileUtils.java:163) -
				an error occurred when read object from /Users/thttnt/Downloads/./config.cfg msg:java.io.FileNotFoundException: ./config.cfg (No such file or directory)
java.io.FileNotFoundException: ./config.cfg (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at cn.ieclipse.util.FileUtils.readObject(FileUtils.java:159)
	at cn.ieclipse.smartim.settings.SmartIMSettings.loadProp(SmartIMSettings.java:43)
	at cn.ieclipse.smartim.dialogs.SettingsDialog.<init>(SettingsDialog.java:63)
	at cn.ieclipse.smartim.dialogs.SettingsDialog.main(SettingsDialog.java:30)
	at cn.ieclipse.smartim.actions.SettingsAction.actionPerformed(SettingsAction.java:21)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
目前就发现这两个错误

测试系统：MacOS
JRE版本: 1.8

**Comment by Jamling** [comment]
1，弹登录窗口，是需要点击“登录”图标的。左侧工具栏第一个就是登录
2，第一次进入设置，会报这个错，因为你从来没有设置过，选项不会保存到config.cfg中。

**Comment by thtTNT** [comment]
1、我知道需要点击登陆，但我找了5分钟。。。应该自动弹出什么的
2、刷错也算是bug吧，为了让代码更加优秀 建议修复

**Comment by thtTNT** [comment]
其实看到你的项目 我觉得QQ For Linux有希望了，我想开发一个QQ For Linux， 希望可以共同努力。

**Comment by thtTNT** [comment]
另外可以的话 给代码添加一个开源协议
Github上如果没有开源协议的话 是不允许使用你的代码的 项目会被删掉的

**Comment by Jamling** [comment]
@thtTNT 如果不使用java，应该不太好开发吧，qt不知道怎么调用jar。

**Comment by thtTNT** [comment]
就是使用java开发啊，其他语言工程量有些大，还要考虑跨平台问题。

**Comment by thtTNT** [comment]
可以的话给个qq或者微信 好联系一下

**Comment by thtTNT** [comment]
发现SmartQQ不支持图片，这个可能比较难办

**Comment by Jamling** [comment]
加群307490913
