### ISSUE TITLE
请求失败，Api返回码[13]

### ISSUE THREAD

**Issue by wsilly** [Jamling/SmartIM#6]
登录成功！
{"retcode":13,"result":{"vfwebqq":"948022398d78b147d09675611a850c817146a94a8dd956dd531fe0dc7b9d92e7a716a7efc95cd5f9"}}
Exception in thread "main" cn.ieclipse.smartim.exception.LogicException: 请求失败，Api返回码[13]
	at com.scienjus.smartqq.client.SmartQQApi.getResponseJson(SmartQQApi.java:595)
	at com.scienjus.smartqq.client.SmartQQApi.getJsonObjectResult(SmartQQApi.java:538)
	at com.scienjus.smartqq.client.SmartQQApi.getAccountInfo(SmartQQApi.java:403)
	at com.scienjus.smartqq.client.SmartQQClient.init(SmartQQClient.java:214)
	at com.scienjus.smartqq.Application.main(Application.java:82)

**Comment by Jamling** [comment]
:cry: SmartQQ 没有开放文档，我也不清楚13表示啥意思

**Comment by Jamling** [comment]
已恢复正常~
